export const COUNTRY_CODES = {
    'Qatar': 'QAT',
    'Brazil': 'BRA',
    'Belgium': 'BEL',
    'France': 'FRA',
    'Argentina': 'ARG',
    'England': 'ENG',
    'Spain': 'ESP',
    'Portugal': 'POR',
    'Mexico': 'MEX',
    'Netherlands': 'NED',
    'Denmark': 'DEN',
    'Germany': 'GER',
    'Uruguay': 'URU',
    'Switzerland': 'SUI',
    'United States': 'USA',
    'Croatia': 'CRO',
    'Senegal': 'SEN',
    'Iran': 'IRN',
    'Japan': 'JPN',
    'Morocco': 'MAR',
    'Serbia': 'SRB',
    'Poland': 'POL',
    'South Korea':'KOR',
    'Tunisia': 'TUN',
    'Cameroon': 'CMR',
    'Canada': 'CAN',
    'Ecuador': 'ECU',
    'Saudi Arabia': 'KSA',
    'Ghana': 'GHA',
    'Wales':'WAL',
    'Costa Rica': 'CRC',
    'Australia': 'AUS'
}